---
title: ""
author: "Nicholas Frumkin"
description: "Gov 50: Final Project"
output:
  distill::distill_article:
    self_contained: false
---

  
```{r}
library(tidyverse)
library("jsonlite")

json_file <- 'https://datahub.io/core/co2-fossil-by-nation/datapackage.json'
json_data <- fromJSON(paste(readLines(json_file), collapse=""))


print(json_data$resources$name)


for(i in 1:length(json_data$resources$datahub$type)){
  if(json_data$resources$datahub$type[i]=='derived/csv'){
    path_to_file = json_data$resources$path[i]
    data1 <- read.csv(url(path_to_file))
    
  }
}

```



```{r}
data1 <- data1 |>
  filter(Year >= 1990, Year <= 2014)


```

```{r}
data_prep1 <- data1 |>
  group_by(Year)|>
  mutate(
    prop_liquid_to_total = (Liquid.Fuel + Gas.Fuel)/Total,
    prop_solid_to_total = Solid.Fuel/Total    
         ) 
```


```{r}
viz1 <- data_prep1 |> 
  group_by(Year) |>
  summarize(
    mean_prop_liquid = mean((prop_liquid_to_total))
  )

viz1 |> ggplot(mapping = aes(x = Year, y = mean_prop_liquid)) + geom_point() + geom_smooth(color = "white")  + theme(panel.background = element_rect(fill = 'steelblue1'))
```

```{r}
viz2 <- data_prep1 |> 
  group_by(Year) |>
  summarize(
    mean_prop_solid = mean((prop_solid_to_total))
  )

viz2 |> ggplot(mapping = aes(x = Year, y = mean_prop_solid)) + geom_point() + geom_smooth(color = "white")  + theme(panel.background = element_rect(fill = 'steelblue1'))

```


```{r}
viz3 <- data1 |> 
  filter(Country == "UNITED STATES OF AMERICA") |>
  group_by(Year) |>
  summarize(
    mean_prop_solid = mean((prop_solid_to_total))
  )

viz3 |> ggplot(mapping = aes(x = Year, y = mean_prop_solid)) + geom_point() + geom_smooth(color = "white")  + theme(panel.background = element_rect(fill = 'steelblue1'))

```


```{r}
viz4 <- data1 |> 
  filter(Country == "CHINA (MAINLAND)") |>
  group_by(Year) |>
  summarize(
    mean_prop_solid = mean((prop_solid_to_total))
  )

viz4 |> ggplot(mapping = aes(x = Year, y = mean_prop_solid)) + geom_point() + geom_smooth(color = "white")  + theme(panel.background = element_rect(fill = 'steelblue1'))
```

```{r}

viz5 <- data1 |> 
  filter(Country == "UNITED STATES OF AMERICA") |>
  group_by(Year) |>
  summarize(
    mean_prop_liquid = mean((prop_liquid_to_total))
  )

viz5 |> ggplot(mapping = aes(x = Year, y = mean_prop_liquid)) + geom_point() + geom_smooth(color = "white")  + theme(panel.background = element_rect(fill = 'steelblue1'))
```


```{r}
viz6 <- data1 |> 
  filter(Country == "CHINA (MAINLAND)") |>
  group_by(Year) |>
  summarize(
    mean_prop_liquid = mean((prop_liquid_to_total))
  )

viz6 |> ggplot(mapping = aes(x = Year, y = mean_prop_liquid)) + geom_point() + geom_smooth(color = "white")  + theme(panel.background = element_rect(fill = 'steelblue1'))


```















